# Site settings
title: Richard Tran
email: contact@richardptran.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer. Currently a Rutgers student pursuing my bachelors in Computer Science (B.S)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.richardptran.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  RichardTran

# Build settings
markdown: kramdown
